name: Scrape Data

on:
  schedule:
    - cron:  '0 8 * * *'

  workflow_dispatch:

jobs:
  scrape:
    name: Scrape Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Scrapy
        run: pip install scrapy

      - name: Fetch latest data
        run: scrapy runspider scraper/spiders/meetingScraper.py --loglevel=INFO -O index.json

      - name: Commit changes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: data
          folder: .
          commit-message: "Update data"

  trigger-rebuild:
    needs: scrape
    name: Build & Deploy Site
    runs-on: ubuntu-latest

    steps:
      - name: Trigger rebuild
        run: https://api.vercel.com/v1/integrations/deploy/prj_bjjjFEReVfuAAysixfiYino2HSn9/iMLmv5J1Fc
