name: Scrape Data

on:
  schedule:
    - cron:  '0 8 * * *'

  workflow_dispatch:

jobs:
  scrape:
    name: Scrape Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Scrapy
        run: pip install scrapy

      - name: Fetch latest data
        run: scrapy runspider scraper/spiders/meetingScraper.py --loglevel=INFO -O index.json

      - name: Commit changes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          target-folder: data
          clean: false
          commit-message: "Update data"
