name: Scrape Data & Rebuild Site

on:
  schedule:
    - cron:  '0 8 * * *'

  workflow_dispatch:

jobs:
  job1:
    name: Scrape Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Scrapy
        run: pip install scrapy

      - name: Fetch latest data
        run: scrapy runspider scraper/spiders/meetingScraper.py --loglevel=INFO -O index.json

      - name: Commit changes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          target-folder: data
          clean: false
          commit-message: "Update data"

  job2:
    needs: job1
    name: Build & Deploy Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          COMMIT_MESSAGE: "Deploy to gh-pages"
          CLEAN: true
          SINGLE_COMMIT: true
